tasks:
  - name: Start MySQL + phpMyAdmin
    init: |
      cd infrastructure/mysql
      docker-compose up -d
    command: |
      echo "✅ MySQL and phpMyAdmin are starting..."
      echo "🔗 phpMyAdmin URL: $(gp url 8080)"
      echo "🗄️  MySQL is running on port 3306"

ports:
  - port: 3306
    onOpen: ignore
    description: MySQL Server

  - port: 8082
    onOpen: open-preview
    description: phpMyAdmin Web UI

vscode:
  extensions:
    - formulahendry.vscode-mysql
