tasks:
  - name: Start Docker Containers
    init: |
      docker-compose up -d

    command: |
      echo "✅ Services started"
      echo "🔗 phpMyAdmin: $(gp url 80)"
      echo "🗄️  Databases: project1_db, project2_db, project3_db"
      echo "🔐 MySQL User: dev / devpass123"

ports:
  - port: 3306
    onOpen: ignore
    description: MySQL Database
  - port: 80
    onOpen: open-preview
    description: phpMyAdmin Interface

vscode:
  extensions:
    - formulahendry.vscode-mysql
