version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: workspace-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password123
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: workspace-phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: password123
    ports:
      - "8080:80"
    depends_on:
      - mysql
